name: Yarn CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.1
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.1
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.1
        with:
          cmd: electron-webpack && electron-builder --linux
